########### 
# PQ2. Retrieve PRO with cleaved form. 
########### 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
 
SELECT
   ?PRO_term
   (str(?_Label) as ?Label)
   (strafter(strbefore(str(?_Category), "."), "=") as ?Category) 
FROM <http://purl.obolibrary.org/obo/pr>
WHERE
{
   ?PRO_term rdfs:label ?_Label .
   ?PRO_term rdfs:comment ?_Category .
   FILTER (regex(?_Category,"Category=.*modification") && regex(?_Label, "cleaved"))
}
